### ISSUE TITLE
Bounds for dependencies seem incorrect

### ISSUE THREAD

**Issue by phlummox** [haskell-github-trust/replace-megaparsec#36]
The Cabal file for `replace-megaparsec` states simply that [`megaparsec` is a dependency](https://github.com/jamesdbrock/replace-megaparsec/blob/703baa90b8cbf1b4910a985409094192bbcb0838/replace-megaparsec.cabal#L28), but that seems incorrect: in fact, versions of megaparsec will have to at least be >= 7.0.0 to work.

This because the code for `replace-megaparsec` uses the [`anySingle`](https://hackage.haskell.org/package/megaparsec-9.0.1/docs/Text-Megaparsec.html#v:anySingle) function, introduced in megaparsec 7.0.0.

Thus, the Cabal file should give the dependency as:

```
    , megaparsec >= 7.0.0
```

(The bounds might in fact be tighter than that; I haven't checked whether megaparsec 7.0.0 will in fact work.)

**Comment by jamesdbrock** [comment]
thanks for making this issue! ill check it out.

**Comment by jamesdbrock** [comment]
Done
